### ISSUE TITLE
Wireguard Grafana Dashboard with no data

### ISSUE THREAD

**Issue by lorenzomonta** [bryopsida/wireguard-chart#45]
Hello, @bryopsida the Wireguard VPN is up an and running! So thank you very much!
Unfortunately I can't the graphs related to the grafana dashboard. I see the Wireguard dashboard but this has all the fields with no data.
Before installing wireguard I already had prometheus installed with grafana to view graphs, I installed this: [https://github.com/prometheus-operator/prometheus-operator](url) so It installed Prometheus, ServiceMonitor, etc. and I can see all graphs in the Grafana's dashboard.
Wireguard is within the namespace wireguard and prometheus is within the prometheus namespace. I installed wireguard with the metrics parameter enabled, but did not specify any other parameters. Can this create the issue?
I went into the prometheus microservice and into `/metrics` and I can see that it correctly collects and exports all the data so I assume/think the problem is on Grafana.

![Wireguard - Dashboards - Grafana](https://github.com/bryopsida/wireguard-chart/assets/48455647/9e9e1fba-907f-425a-b0a4-94f8ab55bab8)

I thank you for your help, I am sorry if I am troubling you a lot these weeks.

**Comment by bryopsida** [comment]
If you check the metrics explorer in grafana do you see any metrics prefixed with `wireguard_`

![image](https://github.com/bryopsida/wireguard-chart/assets/8363252/1c634209-50fe-483a-92e3-4f6f116a72a0)

If not, the issue is probably with prometheus discovering (or being told about) the metrics end point.

If you go to the targets list in prometheus do you see one for wireguard?

![image](https://github.com/bryopsida/wireguard-chart/assets/8363252/f62235dc-1b8d-4277-a455-8a323391f13b)

**Comment by bryopsida** [comment]
The service monitor object configuration is managed by these values: https://github.com/bryopsida/wireguard-chart/blob/5929db46ae0a995fbc7433630b8f9eeb41901979/helm/wireguard/values.yaml#L168

If you don't see that service monitor in prometheus it will not scrape the metrics from the pods.  Try using the namespace setting to create the service monitor in the same namespace as prometheus. This would rule out a permission error where prometheus doesn't have the needed permissions in the wireguard namespace to discover the service monitor.

**Comment by lorenzomonta** [comment]
The problem is exactly this, in fact both under explorer and in the targets list in prometheus. So, I added the following configuration to the values:

```
metrics:
  # -- Enable exposing Wireguard metrics
  enabled: true
  serviceMonitor:
    # -- Create ServiceMonitor Resource for scraping metrics using PrometheusOperator
    enabled: true
    # -- Metrics service HTTP port
    port: exporter
    # -- The endpoint configuration of the ServiceMonitor. Path is mandatory. Interval, timeout and relabelings can be overwritten.
    path: "/metrics"
    # -- Namespace of the ServiceMonitor. If empty, current namespace is used
    namespace: "prometheus"  
  dashboard:
    annotations:
      k8s-sidecar-target-directory: /tmp/dashboards
```

So I run: `helm upgrade wg-vpn-1 wireguard/wireguard --namespace wireguard -f /path` to update the configuration.
However, I'm not sure if I got the new changes because it doesn't work for me. Maybe I need to delete everything and reinstall everything?
I tried restarting all the pods as well.

I saw that there is an option to enter the namespace under prometheusRule as well, should I put it here as well?
```
prometheusRule:
  # -- Create PrometheusRule Resource for scraping metrics using PrometheusOperator
  enabled: false
  # -- Namespace of the ServiceMonitor. If empty, current namespace is used
  namespace: ""
```

Thank you

**Comment by bryopsida** [comment]
`Maybe I need to delete and reinstall in the wireguard namespace?` That shouldn't be necessary, the prometheus operator should be watching for all service monitor changes and updating the prometheus config to match the defined monitors.

Has the prometheus install been able to discover over external service monitors? You may want to test out manually setting a scrape config, and see if that works.

 For example if you use the kube-prometheus-stack: https://github.com/prometheus-community/helm-charts/blob/e4588e35952ebccedd028bcdcdc7dacf4720ba91/charts/kube-prometheus-stack/values.yaml#L3595

**Comment by lorenzomonta** [comment]
Yes I am using exactly that! Unfortunately I am not familiar with Prometheus, I understood that I should add a scrape configuration for the Prometheus operator to read these additional configurations and apply them together with the main configuration.
If you would do me the courtesy of helping me use a basic scrape config I would be very grateful

`Has the prometheus install been able to discover other external service monitors? `  I do not use any other external services at the moment

**Comment by lorenzomonta** [comment]
I don't want to take too much advantage of your kindness

**Comment by bryopsida** [comment]
If you used the `kube-prom-stack` helm chart, you'd could add an additional scrape config with this value fragment.

``` yaml
prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: 'kubernetes-pods'
        scrape_interval: 30s
        kubernetes_sd_configs:
        - role: pod
        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
          target_label: __address__
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: kubernetes_namespace
        - source_labels: [__meta_kubernetes_pod_name]
          action: replace
          target_label: kubernetes_pod_name
```

Then on the wireguard helm release update to add a few annotations for pod discovery.

wireguard value fragment to add annotations
``` yaml
podAnnotations:
  prometheus.io/scrape: true
  prometheus.io/path: /metrics
  prometheus.io/port: 9586
```
