### ISSUE TITLE
WireGuard client unable to resolve DNS, e.g., redis.redis.svc.cluster.local

### ISSUE THREAD

**Issue by blgdmbrl** [bryopsida/wireguard-chart#63]
Hi, WireGuard client unable to resolve DNS, e.g., redis.redis.svc.cluster.local

My server yaml is

```yaml
replicaCount: 1
autoscaling:
  enabled: false

service:
  enabled: true
  type: ClusterIP
wireguard:
  serverAddress: 172.32.32.1/24
  serverCidr: 172.32.32.0/24
  clients:
  - AllowedIPs: 172.32.32.2/32
    PublicKey: iaWRm9zdDyM95FXgoUpGNI2seN7vXyoQVG78ODGGJHY=
```

I checked the wg pod and run `wg show wg0` and it's working fine
```bash
$ sudo wg show wg0
interface: wg0
  public key: EsPzisDRhRc5cpVHg5TSjfnWWkA6m82nhKczIxcZtU8=
  private key: (hidden)
  listening port: 51820

peer: iaWRm9zdDyM95FXgoUpGNI2seN7vXyoQVG78ODGGJHY=
  endpoint: 10.0.1.107:57281
  allowed ips: 172.32.32.2/32
  latest handshake: 10 seconds ago
  transfer: 173.18 KiB received, 248.56 KiB sent
```
  
from the pod I tried to nslookup, and it works fine.

```bash
~ $ nslookup redis.redis.svc.cluster.local
Server:		10.43.0.10
Address:	10.43.0.10:53


Name:	redis.redis.svc.cluster.local
Address: 10.43.113.234
```

and my client config is
```yaml
[Interface]
PrivateKey = oBbcACEL+lThCxwxvjDpYKlSJgX1zsuyHpB8lJf7xmU=
Address = 172.32.32.2/32
DNS = 10.43.0.10, 8.8.8.8

[Peer]
PublicKey = EsPzisDRhRc5cpVHg5TSjfnWWkA6m82nhKczIxcZtU8=
AllowedIPs = 10.0.0.0/16, 10.43.0.0/16, 172.32.32.0/24
Endpoint = 124.158.124.121:51820
PersistentKeepalive = 25
```

the ping works fine to 

```bash
ping 172.32.32.1
PING 172.32.32.1 (172.32.32.1): 56 data bytes
64 bytes from 172.32.32.1: icmp_seq=0 ttl=64 time=9.281 ms
64 bytes from 172.32.32.1: icmp_seq=1 ttl=64 time=9.031 ms
64 bytes from 172.32.32.1: icmp_seq=2 ttl=64 time=13.573 ms
```

but it couldn't reach the  `nslookup redis.redis.svc.cluster.local`, and I tried to traceroute to `10.43.113.234`

```bash
traceroute 10.43.113.234
traceroute to 10.43.113.234 (10.43.113.234), 64 hops max, 52 byte packets
 1  172.32.32.1 (172.32.32.1)  6.532 ms  8.060 ms  7.810 ms
 2  * * * *
 ```
 
and I can't fix this, help my guys. I wanna connect to 10.43.* from my client (DNS is optional). I'm using k3s + cilium
