### ISSUE TITLE
error setting key 'net.ipv4.conf.all.src_valid_mark': Read-only file system

### ISSUE THREAD

**Issue by brandonros** [bryopsida/wireguard-chart#65]
```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: wireguard
  namespace: kube-system
spec:
  repo: https://bryopsida.github.io/wireguard-chart/
  chart: wireguard
  createNamespace: true
  targetNamespace: wireguard
  valuesContent: |-
    replicaCount: 1
    autoscaling:
      enabled: false
    wireguard:
      serverAddress: 10.34.0.1/24
      serverCidr: 10.34.0.0/24
      natAddSourceNet: true
      interfaceOpts: {}
      clients: 
        - FriendlyName: client1
          AllowedIPs: 0.0.0.0/0
          PublicKey: redacted
          PersistentKeepalive: 25
```

```
sysctls net.ipv4.ip_forward = 1
sysctls net.ipv4.conf.all.forwarding = 1
wireguard [#] ip link add wg0 type wireguard
wireguard [#] wg setconf wg0 /dev/fd/63
wireguard [#] ip -4 address add 10.34.0.1/24 dev wg0
wireguard [#] ip link set mtu 1370 up dev wg0
wireguard [#] wg set wg0 fwmark 51820
wireguard [#] ip -4 route add 0.0.0.0/0 dev wg0 table 51820
wireguard [#] ip -4 rule add not fwmark 51820 table 51820
wireguard [#] ip -4 rule add table main suppress_prefixlength 0
wireguard [#] sysctl -q net.ipv4.conf.all.src_valid_mark=1
wireguard sysctl: error setting key 'net.ipv4.conf.all.src_valid_mark': Read-only file system
wireguard [#] ip -4 rule delete table 51820
wireguard [#] ip -4 rule delete table main suppress_prefixlength 0
wireguard [#] ip link delete dev wg0
wireguard Public key 'redacted'
│ stream closed EOF for wireguard/wireguard-wireguard-db9974876-s85hk (sysctls)
wireguard wg-quick: `wg0' is not a WireGuard interface
│ stream closed EOF for wireguard/wireguard-wireguard-db9974876-s85hk (wireguard)       
```
