### ISSUE TITLE
LoadBalancers not registering the targets - Unhealthy instances

### ISSUE THREAD

**Issue by cmarquezrusso** [bryopsida/wireguard-chart#70]
Hi @bryopsida 
First things first, thanks for developing this chart.

I am currently testing this on a AWS EKS cluster. I am using nodes that are hosting other applications (Webapps). 
Then, I expose this service via an AWS Load Balancer. I've added annotations in other to create an internet facing network load balancer. However this is showing unhealthy hosts. 

Ive also tried with the default values file but still no luck. 

Kubernetes: v1.30.8-eks-2d5f260
Helm: v3.17.0 (Locally, I am using ArgoCD for Deployment tho)
Nodes: Amazon Linux 2 - min v1.30.2-eks-1552ad0 - max v1.30.7-eks-59bf375

LoadBalancer Config:
aws-load-balancer-controller:v2.8.1
```
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
```

From AWS Console, I can see that the loadbalancer is listening on port UDP 51820 and targets are the k8s instances on port 32286

Nodes are healthy when I run `nc -l 32286`, just showing that the port is not used by the wireguard container but they are not crashing. 

Do I need to add extra permissions in order to open that port?

**Comment by bryopsida** [comment]
If I'm following correctly the issue is the nodes in the target group for the LB aren't registering as healthy when looking at the LB in the AWS console?

What health check mechanism do you have configured at the LB level? You may want to look into using the health check side car which exposes a http health check route you can use at the node level that's linked to the state of the pod.  It's enabled using this value: https://github.com/bryopsida/wireguard-chart/blob/5d283a3139c39f7c132855af8bf0698c151b16d8/helm/wireguard/values.yaml#L278

There's 2 value file examples.

If you using a daemonset
https://github.com/bryopsida/wireguard-chart/blob/main/ci/test-with-healthsidecar-daemonset-hostport.yaml

If you are using a deployment
https://github.com/bryopsida/wireguard-chart/blob/main/ci/test-with-healthsidecar-nodeport.yaml

**Comment by bryopsida** [comment]
You likely will need to adjust the LB annotations to point it at the health check EP.

https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/ingress/annotations/

**Comment by cmarquezrusso** [comment]
I tried with those recommendations but still no luck. I've deleted and recreated the load balancer but still getting the same results: unhealthy instances

<img width="954" alt="Image" src="https://github.com/user-attachments/assets/3f129f35-90de-4716-bd2b-aae562eaa3da" />

I am running this on a dedicated instance now, r7a.large amd64 with AL2

My LB annotations look like this: 
```
annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "3000"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: "TCP"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: "/health"
```

LB Config looks like this:

<img width="413" alt="Image" src="https://github.com/user-attachments/assets/b99d8819-efc4-4966-a357-d770c9b83fb6" />

And the target group looks like this

![Image](https://github.com/user-attachments/assets/84c64a9a-a339-402e-a9e9-f8c5b5e135ee)
