### ISSUE TITLE
Please, clarify how to load config.

### ISSUE THREAD

**Issue by DaBlitzStein** [bryopsida/wireguard-chart#76]
I have been using values.yaml file:
```
wireguard:
  enabled: true
  port: 51820
  serverAddress: "10.34.0.1/24"

  privateKeySecretName: "wg-vpn-1-wg-generated"
  dns: "10.96.0.10"
  clients:
    - PublicKey: "ww"
      AllowedIPs: "10.34.0.5/32"
    - PublicKey: "ww"
      AllowedIPs: "10.34.0.2/32"
    - PublicKey: "ww"
      AllowedIPs: "10.34.0.4/32"

service:
  type: LoadBalancer 
  port: 51820 
```
But it looks like it is ignoring everything. 

Maybe I am not configuring it right?
